# fly.toml app configuration file generated for grantpilot-1ak4uw on 2026-03-01T14:36:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grantpilot-1ak4uw'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
