export type DefaultGrantSourceSeed = {
  sourceName: string;
  endpoint: string;
  country: string;
  type: "rss" | "government_portal" | "foundation" | "newsletter";
  crawlFrequency: "6h" | "24h" | "72h" | "168h";
  notes: string;
};

export const DEFAULT_UK_EU_GLOBAL_GRANT_SOURCE_SEEDS: DefaultGrantSourceSeed[] = [
  {
    sourceName: "UKRI Funding Finder",
    endpoint: "https://www.ukri.org/opportunity/",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official UKRI opportunity listing for UK research, innovation, business and collaboration funding.",
  },
  {
    sourceName: "Innovate UK Competition Search",
    endpoint: "https://apply-for-innovation-funding.service.gov.uk/competition/search",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official Innovate UK competition search for UK businesses and innovation projects.",
  },
  {
    sourceName: "Find a Grant Opportunities",
    endpoint: "https://www.find-government-grants.service.gov.uk/grants",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official UK Government grant listing service.",
  },
  {
    sourceName: "Scottish Enterprise Funding and Grants",
    endpoint: "https://www.scottish-enterprise.com/support-for-businesses/funding-and-grants",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official Scottish Enterprise funding page for businesses.",
  },
  {
    sourceName: "Business Wales Funding and Grants",
    endpoint: "https://businesswales.gov.wales/funding-and-grants",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official Welsh business funding and grants portal.",
  },
  {
    sourceName: "Invest Northern Ireland Support for Business",
    endpoint: "https://www.investni.com/support-for-business",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official Northern Ireland business support and funding source.",
  },
  {
    sourceName: "UK Space Agency Funding",
    endpoint: "https://www.gov.uk/guidance/apply-for-funding-academic-community-and-educational",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official UK Space Agency page for academic, community, education, SME and organisation funding opportunities.",
  },
  {
    sourceName: "UK Defence Innovation Live Funding Opportunities",
    endpoint: "https://www.gov.uk/government/collections/live-funding-opportunities",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official UK defence innovation live competition and funding opportunity collection.",
  },
  {
    sourceName: "Arts Council of Northern Ireland Funding",
    endpoint: "https://artscouncil-ni.org/funding",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official Arts Council of Northern Ireland funding programmes and open calls.",
  },
  {
    sourceName: "British Council HE and Science Opportunities",
    endpoint: "https://www.britishcouncil.org/education/he-science/opportunities",
    country: "UK",
    type: "foundation",
    crawlFrequency: "24h",
    notes: "British Council grants, funding and international collaboration opportunities for UK institutions, researchers and organisations.",
  },
  {
    sourceName: "East Ayrshire Business Grants",
    endpoint: "https://www.east-ayrshire.gov.uk/BusinessAndTrade/Business-support/Grant-and-funding-support.aspx",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official East Ayrshire business grant and funding support page for SMEs and local businesses.",
  },
  {
    sourceName: "Three Rivers Sustainable Business Grants",
    endpoint: "https://www.threerivers.gov.uk/services/environment-climate-emergency/sustainable-business",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official Three Rivers sustainable business grants and support page.",
  },
  {
    sourceName: "Arun Business Grants and Funding",
    endpoint: "https://www.arun.gov.uk/leap/",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official Arun local enterprise and business grants page.",
  },
  {
    sourceName: "North Lanarkshire Town Centre Retail Business Fund",
    endpoint: "https://www.northlanarkshire.gov.uk/business/business-support/town-centre-retail-business-fund",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official North Lanarkshire SME and startup town-centre retail business fund page.",
  },
  {
    sourceName: "National Lottery Community Fund Funding Programmes",
    endpoint: "https://www.tnlcommunityfund.org.uk/funding/funding-programmes",
    country: "UK",
    type: "foundation",
    crawlFrequency: "24h",
    notes: "UK National Lottery Community Fund grant programme listing.",
  },
  {
    sourceName: "Greater London Authority Grants",
    endpoint: "https://www.london.gov.uk/programmes-strategies/funding-and-grants",
    country: "UK",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "Official London grants and funding page.",
  },
  {
    sourceName: "Nesta Funding",
    endpoint: "https://www.nesta.org.uk/funding/",
    country: "UK",
    type: "foundation",
    crawlFrequency: "24h",
    notes: "UK innovation foundation funding page.",
  },
  {
    sourceName: "Wellcome Grant Funding",
    endpoint: "https://wellcome.org/grant-funding",
    country: "UK",
    type: "foundation",
    crawlFrequency: "24h",
    notes: "UK-based global health and research funder.",
  },
  {
    sourceName: "EU Funding and Tenders Calls",
    endpoint: "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/calls-for-proposals",
    country: "EU",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "European Commission calls for proposals, including programmes open to UK or international partners where eligible.",
  },
  {
    sourceName: "Horizon Europe Open Calls",
    endpoint: "https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe_en",
    country: "EU",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "European Commission Horizon Europe programme page.",
  },
  {
    sourceName: "European Innovation Council Funding",
    endpoint: "https://eic.ec.europa.eu/eic-funding-opportunities_en",
    country: "EU",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "European Innovation Council funding opportunities for startups and innovation projects.",
  },
  {
    sourceName: "Eurostars Programme",
    endpoint: "https://www.eurekanetwork.org/programmes/eurostars/",
    country: "EU",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "International innovation funding programme with UK participation routes where calls allow.",
  },
  {
    sourceName: "Eureka Network Open Calls",
    endpoint: "https://www.eurekanetwork.org/open-calls/",
    country: "EU",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "International R&D and innovation open calls across Eureka countries.",
  },
  {
    sourceName: "Interreg Europe Calls",
    endpoint: "https://www.interregeurope.eu/apply-for-funding",
    country: "EU",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "European territorial cooperation funding calls.",
  },
  {
    sourceName: "Creative Europe Calls",
    endpoint: "https://culture.ec.europa.eu/calls",
    country: "EU",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "European Commission culture and creative sector calls.",
  },
  {
    sourceName: "Digital Europe Programme Calls",
    endpoint: "https://digital-strategy.ec.europa.eu/en/activities/digital-programme",
    country: "EU",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "European digital transformation funding programme.",
  },
  {
    sourceName: "Single Market Programme Calls",
    endpoint: "https://commission.europa.eu/funding-tenders/find-funding/eu-funding-programmes/single-market-programme/overview/calls-proposals_en",
    country: "EU",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "European Commission Single Market Programme calls for proposals, relevant to SMEs and cross-border applicants where eligible.",
  },
  {
    sourceName: "ESA Space Solutions Funding",
    endpoint: "https://business.esa.int/funding",
    country: "EU",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "European Space Agency business applications and space solutions funding routes open to eligible European and UK participants.",
  },
  {
    sourceName: "NATO DIANA Challenges",
    endpoint: "https://www.diana.nato.int/challenges.html",
    country: "XX",
    type: "government_portal",
    crawlFrequency: "24h",
    notes: "NATO DIANA challenge programme for dual-use deep-tech startups and innovators from participating Allied countries including the UK.",
  },
  {
    sourceName: "Global Innovation Fund Apply",
    endpoint: "https://www.globalinnovation.fund/apply/",
    country: "XX",
    type: "foundation",
    crawlFrequency: "24h",
    notes: "Global programme accepting international applicants for innovation impact funding.",
  },
  {
    sourceName: "Mozilla Awards and Grants",
    endpoint: "https://www.mozilla.org/en-US/moss/",
    country: "XX",
    type: "foundation",
    crawlFrequency: "72h",
    notes: "Global open-source grant programme.",
  },
  {
    sourceName: "Internet Society Foundation Grants",
    endpoint: "https://www.isocfoundation.org/grant-programme/",
    country: "XX",
    type: "foundation",
    crawlFrequency: "72h",
    notes: "Global foundation grant programmes with international applicant routes.",
  },
  {
    sourceName: "Grand Challenges Funding Opportunities",
    endpoint: "https://grandchallenges.org/grant-opportunities/",
    country: "XX",
    type: "foundation",
    crawlFrequency: "24h",
    notes: "Global health and innovation challenge funding opportunities.",
  },
  {
    sourceName: "Brain Research UK Apply for a Grant",
    endpoint: "https://www.brainresearchuk.org.uk/research/apply",
    country: "UK",
    type: "foundation",
    crawlFrequency: "72h",
    notes: "UK brain research grant application page with recurring project grant rounds and collaboration routes.",
  },
  {
    sourceName: "BMA Foundation Grant Categories",
    endpoint: "https://www.bmafoundationmr.org.uk/grant-categories/",
    country: "UK",
    type: "foundation",
    crawlFrequency: "72h",
    notes: "BMA Foundation medical research grant category listing for UK-led research applicants.",
  },
  {
    sourceName: "Colt Foundation Project Grants",
    endpoint: "https://www.coltfoundation.org.uk/project-grants/",
    country: "UK",
    type: "foundation",
    crawlFrequency: "72h",
    notes: "UK project grant page for occupational and environmental health research funding.",
  },
  {
    sourceName: "Elrha Funding",
    endpoint: "https://www.elrha.org/funding",
    country: "XX",
    type: "foundation",
    crawlFrequency: "24h",
    notes: "Global humanitarian innovation funding opportunities.",
  },
];
