-- Curated grant sources from user list. Deduplicated: excludes URLs already in 025 and 027.
-- All use adapter 'crawl'. type: government_portal, foundation, or newsletter.

INSERT INTO grant_sources (id, source_name, country, type, endpoint, crawl_frequency, enabled, adapter)
VALUES
  ('gs-innovate-uk-apply', 'Innovate UK Apply for Funding', 'UK', 'government_portal', 'https://apply-for-innovation-funding.service.gov.uk', '24h', true, 'crawl'),
  ('gs-ukri-international', 'UKRI International Funding', 'UK', 'government_portal', 'https://www.ukri.org/what-we-do/international-funding/', '24h', true, 'crawl'),
  ('gs-find-a-grant-home', 'Find a Grant', 'UK', 'government_portal', 'https://www.find-government-grants.service.gov.uk', '24h', true, 'crawl'),
  ('gs-sport-england', 'Sport England Funding', 'UK', 'government_portal', 'https://www.sportengland.org/funding-and-campaigns/our-funding', '24h', true, 'crawl'),
  ('gs-nesta', 'Nesta Funding', 'UK', 'foundation', 'https://www.nesta.org.uk/funding/', '24h', true, 'crawl'),
  ('gs-wellcome-research', 'Wellcome Research Funding', 'UK', 'foundation', 'https://wellcome.org/research-funding', '24h', true, 'crawl'),
  ('gs-arts-council-project', 'Arts Council England Project Grants', 'UK', 'government_portal', 'https://www.artscouncil.org.uk/projectgrants', '24h', true, 'crawl'),
  ('gs-heritage-fund', 'National Heritage Lottery Fund', 'UK', 'government_portal', 'https://www.heritagefund.org.uk/funding', '24h', true, 'crawl'),
  ('gs-energy-saving-trust', 'Energy Saving Trust Grants', 'UK', 'government_portal', 'https://energysavingtrust.org.uk/grants-and-loans/', '24h', true, 'crawl'),
  ('gs-scottish-enterprise-grants', 'Scottish Enterprise Funding and Grants', 'UK', 'government_portal', 'https://www.scottish-enterprise.com/support-for-businesses/funding-and-grants', '24h', true, 'crawl'),
  ('gs-business-wales', 'Business Wales Funding Locator', 'UK', 'government_portal', 'https://businesswales.gov.wales/funding-and-grants', '24h', true, 'crawl'),
  ('gs-invest-ni', 'Invest Northern Ireland Support', 'UK', 'government_portal', 'https://www.investni.com/support-for-business', '24h', true, 'crawl'),
  ('gs-london-mayor', 'London Mayor Funding', 'UK', 'government_portal', 'https://www.london.gov.uk/what-we-do/grants', '24h', true, 'crawl'),
  ('gs-simpler-grants', 'Simpler Grants.gov Search', 'US', 'government_portal', 'https://simpler.grants.gov/search', '24h', true, 'crawl'),
  ('gs-nsf-seed-fund', 'NSF Seed Fund', 'US', 'government_portal', 'https://seedfund.nsf.gov', '24h', true, 'crawl'),
  ('gs-usa-gov-grants', 'USA.gov Grants and Loans', 'US', 'government_portal', 'https://www.usa.gov/grants', '24h', true, 'crawl'),
  ('gs-senate-crs', 'U.S. Senate CRS Grants Guide', 'US', 'government_portal', 'https://www.senate.gov/CRS/grants.htm', '72h', true, 'crawl'),
  ('gs-nih-funding', 'NIH Grants & Funding', 'US', 'government_portal', 'https://grants.nih.gov/funding/index.htm', '24h', true, 'crawl'),
  ('gs-doe-eere', 'DOE EERE Funding Opportunities', 'US', 'government_portal', 'https://www.energy.gov/eere/funding/eere-funding-opportunities', '24h', true, 'crawl'),
  ('gs-usda-rd', 'USDA Rural Development Grants', 'US', 'government_portal', 'https://www.rd.usda.gov/programs-services/all-programs', '24h', true, 'crawl'),
  ('gs-nasa-spirs', 'NASA SPRS Solicitation and Proposal', 'US', 'government_portal', 'https://solicitation.nasaprs.com', '24h', true, 'crawl'),
  ('gs-ed-forecast', 'ED Grants Forecast', 'US', 'government_portal', 'https://www2.ed.gov/fund/grant/find/edlite-forecast.html', '24h', true, 'crawl'),
  ('gs-epa-grants', 'EPA Grants', 'US', 'government_portal', 'https://www.epa.gov/grants', '24h', true, 'crawl'),
  ('gs-neh-grants', 'NEH Grants', 'US', 'government_portal', 'https://www.neh.gov/grants', '24h', true, 'crawl'),
  ('gs-sba-funding', 'SBA Funding Programs', 'US', 'government_portal', 'https://www.sba.gov/funding-programs', '24h', true, 'crawl'),
  ('gs-california-grants', 'California Grants Portal', 'US', 'government_portal', 'https://www.grants.ca.gov/', '24h', true, 'crawl'),
  ('gs-texas-egrants', 'Texas eGrants', 'US', 'government_portal', 'https://egrants.gov.texas.gov/', '24h', true, 'crawl'),
  ('gs-ny-grants', 'New York State Grants Gateway', 'US', 'government_portal', 'https://grantsgateway.ny.gov/', '24h', true, 'crawl'),
  ('gs-florida-grants', 'Florida Grants', 'US', 'government_portal', 'https://www.flgov.com/', '24h', true, 'crawl'),
  ('gs-pa-egrants', 'Pennsylvania eGrants', 'US', 'government_portal', 'https://www.esa.dced.state.pa.us/Login.aspx', '24h', true, 'crawl'),
  ('gs-ohio-grants', 'Ohio Development Grants', 'US', 'government_portal', 'https://development.ohio.gov/', '24h', true, 'crawl'),
  ('gs-mass-grants', 'Massachusetts Grants', 'US', 'government_portal', 'https://www.mass.gov/grants', '24h', true, 'crawl'),
  ('gs-nj-grants', 'New Jersey Grants', 'US', 'government_portal', 'https://www.nj.gov/grants', '24h', true, 'crawl'),
  ('gs-colorado-grants', 'Colorado Grants', 'US', 'government_portal', 'https://grants.colorado.gov/', '24h', true, 'crawl'),
  ('gs-washington-grants', 'Washington State Grants', 'US', 'government_portal', 'https://ofm.wa.gov/budget/grants', '24h', true, 'crawl'),
  ('gs-eu-portal-home', 'EU Funding & Tenders Portal', 'EU', 'government_portal', 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/home', '24h', true, 'crawl'),
  ('gs-eu-calls', 'EU Calls for Proposals', 'EU', 'government_portal', 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/calls-for-proposals', '24h', true, 'crawl'),
  ('gs-eu-programmes', 'EU Programmes Directory', 'EU', 'government_portal', 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/programmes', '24h', true, 'crawl'),
  ('gs-eu-ri-open-calls', 'EU Research & Innovation Open Calls', 'EU', 'government_portal', 'https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls_en', '24h', true, 'crawl'),
  ('gs-horizon-europe-ri', 'Horizon Europe', 'EU', 'government_portal', 'https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe_en', '24h', true, 'crawl'),
  ('gs-eic-portal', 'European Innovation Council', 'EU', 'government_portal', 'https://eic.ec.europa.eu', '24h', true, 'crawl'),
  ('gs-erc', 'European Research Council', 'EU', 'government_portal', 'https://erc.europa.eu/homepage', '24h', true, 'crawl'),
  ('gs-european-funding-guide', 'European Funding Guide', 'EU', 'newsletter', 'https://www.european-funding-guide.eu/', '72h', true, 'crawl'),
  ('gs-foerderdatenbank', 'Germany Federal Funding Database', 'EU', 'government_portal', 'https://www.foerderdatenbank.de', '24h', true, 'crawl'),
  ('gs-bpi-france', 'BPI France Funding', 'EU', 'government_portal', 'https://www.bpifrance.fr', '24h', true, 'crawl'),
  ('gs-anr-france', 'ANR France Calls', 'EU', 'government_portal', 'https://anr.fr/en/latest-news/read/news/', '24h', true, 'crawl'),
  ('gs-cdti-spain', 'CDTI Spain Grants', 'EU', 'government_portal', 'https://www.cdti.es', '24h', true, 'crawl'),
  ('gs-enisa-spain', 'ENISA Spain Funding', 'EU', 'government_portal', 'https://www.enisa.es', '24h', true, 'crawl'),
  ('gs-enterprise-ireland', 'Enterprise Ireland Funding', 'EU', 'government_portal', 'https://www.enterprise-ireland.com/en/funding-supports/', '24h', true, 'crawl'),
  ('gs-ida-ireland', 'IDA Ireland Supports', 'EU', 'government_portal', 'https://www.idaireland.com/grow-your-business/supports', '24h', true, 'crawl'),
  ('gs-rvo-netherlands', 'RVO Netherlands Subsidies', 'EU', 'government_portal', 'https://www.rvo.nl/subsidies-financiering', '24h', true, 'crawl'),
  ('gs-vinnova', 'Vinnova Sweden', 'EU', 'government_portal', 'https://www.vinnova.se/en/apply-for-funding/', '24h', true, 'crawl'),
  ('gs-innovation-fund-denmark', 'Innovation Fund Denmark', 'EU', 'government_portal', 'https://innovationsfonden.dk/en/apply-for-a-grant', '24h', true, 'crawl'),
  ('gs-business-finland', 'Business Finland Funding', 'EU', 'government_portal', 'https://www.businessfinland.fi/en/for-finnish-customers/services/funding', '24h', true, 'crawl'),
  ('gs-ffg-austria', 'FFG Austria Funding', 'EU', 'government_portal', 'https://www.ffg.at/en/funding', '24h', true, 'crawl'),
  ('gs-innosuisse', 'Innosuisse Switzerland', 'EU', 'government_portal', 'https://www.innosuisse.admin.ch', '24h', true, 'crawl'),
  ('gs-rc-norway', 'Research Council of Norway Funding', 'EU', 'government_portal', 'https://www.forskningsradet.no/en/apply-for-funding/', '24h', true, 'crawl'),
  ('gs-eufundingportal', 'EUFundingPortal', 'EU', 'newsletter', 'https://eufundingportal.eu', '24h', true, 'crawl'),
  ('gs-gfi-europe', 'GFI Europe Research Funding Database', 'EU', 'newsletter', 'https://gfieurope.org/science/research-funding/', '72h', true, 'crawl'),
  ('gs-gates-foundation', 'Gates Foundation Grants', 'XX', 'foundation', 'https://www.gatesfoundation.org/grants', '24h', true, 'crawl'),
  ('gs-open-society', 'Open Society Foundations Grants', 'XX', 'foundation', 'https://www.opensocietyfoundations.org/grants', '24h', true, 'crawl'),
  ('gs-ford-foundation', 'Ford Foundation Grants', 'XX', 'foundation', 'https://www.fordfoundation.org/work/our-grants/', '24h', true, 'crawl'),
  ('gs-laudes-foundation', 'Laudes Foundation Grants Database', 'XX', 'foundation', 'https://www.laudesfoundation.org/how-we-work/grants-database/', '72h', true, 'crawl'),
  ('gs-rockefeller', 'Rockefeller Foundation Funding', 'XX', 'foundation', 'https://www.rockefellerfoundation.org/grants/', '24h', true, 'crawl'),
  ('gs-hilton-foundation', 'Conrad N. Hilton Foundation Grants', 'XX', 'foundation', 'https://www.hiltonfoundation.org/grants/', '24h', true, 'crawl'),
  ('gs-macarthur', 'MacArthur Foundation Grants', 'XX', 'foundation', 'https://www.macfound.org/grants', '24h', true, 'crawl'),
  ('gs-mastercard-foundation', 'Mastercard Foundation Funding', 'XX', 'foundation', 'https://mastercardfdn.org/grants-and-programs/', '24h', true, 'crawl'),
  ('gs-wellcome-discovery', 'Wellcome Discovery Research', 'XX', 'foundation', 'https://wellcome.org/grant-funding', '24h', true, 'crawl'),
  ('gs-czi', 'Chan Zuckerberg Initiative Funding', 'XX', 'foundation', 'https://chanzuckerberg.com/science/programs-resources/', '24h', true, 'crawl'),
  ('gs-mozilla', 'Mozilla Awards and Grants', 'XX', 'foundation', 'https://www.mozilla.org/en-US/moss/', '24h', true, 'crawl'),
  ('gs-google-org', 'Google.org Impact Challenge', 'XX', 'foundation', 'https://www.google.org', '24h', true, 'crawl'),
  ('gs-cisco-foundation', 'Cisco Foundation Grants', 'XX', 'foundation', 'https://www.cisco.com/c/en/us/about/csr/community/community-impact-grants.html', '24h', true, 'crawl'),
  ('gs-microsoft-ai-accessibility', 'Microsoft AI for Accessibility', 'XX', 'foundation', 'https://www.microsoft.com/en-us/ai/ai-for-accessibility-grants', '24h', true, 'crawl'),
  ('gs-un-women', 'UN Women Calls', 'XX', 'government_portal', 'https://www.unwomen.org/en/how-we-work/programme-implementation/call-for-proposals', '24h', true, 'crawl'),
  ('gs-undp-procurement', 'UNDP Procurement and Calls', 'XX', 'government_portal', 'https://procurement-notices.undp.org/', '24h', true, 'crawl'),
  ('gs-unicef-funding', 'UNICEF Funding Opportunities', 'XX', 'government_portal', 'https://www.unicef.org/partnerships/funding-opportunities', '24h', true, 'crawl'),
  ('gs-world-bank-procurement', 'World Bank Procurement', 'XX', 'government_portal', 'https://projects.worldbank.org/en/projects-operations/products-and-services/procurement-projects-programs', '24h', true, 'crawl'),
  ('gs-idb-calls', 'Inter-American Development Bank Calls', 'XX', 'government_portal', 'https://www.iadb.org/en/how-we-can-work-together/calls-for-proposals', '24h', true, 'crawl'),
  ('gs-afdb-procurement', 'African Development Bank Procurement', 'XX', 'government_portal', 'https://www.afdb.org/en/projects-and-operations/procurement/new', '24h', true, 'crawl'),
  ('gs-adb-opportunities', 'ADB Consulting and Procurement', 'XX', 'government_portal', 'https://www.adb.org/work-with-us/business-opportunities', '24h', true, 'crawl'),
  ('gs-global-innovation-fund', 'Global Innovation Fund', 'XX', 'foundation', 'https://www.globalinnovation.fund/apply/', '24h', true, 'crawl'),
  ('gs-grand-challenges', 'Grand Challenges', 'XX', 'foundation', 'https://grandchallenges.org', '24h', true, 'crawl'),
  ('gs-grantwatch', 'GrantWatch', 'XX', 'newsletter', 'https://www.grantwatch.com', '24h', true, 'crawl'),
  ('gs-fundsforngos', 'FundsforNGOs', 'XX', 'newsletter', 'https://www2.fundsforngos.org', '24h', true, 'crawl'),
  ('gs-openopps', 'OpenOpps', 'XX', 'newsletter', 'https://openopps.com', '24h', true, 'crawl')
ON CONFLICT (id) DO UPDATE SET
  source_name = EXCLUDED.source_name,
  country = EXCLUDED.country,
  type = EXCLUDED.type,
  endpoint = EXCLUDED.endpoint,
  crawl_frequency = EXCLUDED.crawl_frequency,
  enabled = EXCLUDED.enabled,
  adapter = EXCLUDED.adapter,
  updated_at = now();
